### ISSUE TITLE
save playlist: file not containing file paths

### ISSUE THREAD

**Issue by ttqf** [KenT2/tboplayer#142]
hi, have updated to the latest version and it seems that playlist saving is not working properly. the csv file does not contain file paths, only files names.
it is a clean update, removed all files and config.
![playlist](https://user-images.githubusercontent.com/19590440/43966644-b974d152-9cc2-11e8-8c12-50146fbeeef8.jpg)

**Comment by heniotierra** [comment]
It will check this when I get some free time. Thank you.

Em sex, 10 de ago de 2018 12:30, ttqf <notifications@github.com> escreveu:

**Comment by ttqf** [comment]
problem seems to be in this function: `def save_list(self)`
line:
`ofile.write ('"' + (item if 'http' in item else self.playlist.selected_track()[PlayList.LOCATION_BACKUP]) + '","' + self.playlist.selected_track()[PlayList.TITLE]+'"\n')`
should be:
`ofile.write ('"' + (item if 'http' in item else self.playlist.selected_track()[PlayList.LOCATION]) + '","' + self.playlist.selected_track()[PlayList.TITLE]+'"\n')`

with this change it seems to be working. let me know if that should be the fix.

**Comment by heniotierra** [comment]
Actually, I believe the problem is that there a 'not' operator missing before 'http'. Try this:

ofile.write ('"' + (item if not 'http' in item else self.playlist.selected_track()[PlayList.LOCATION_BACKUP]) + '","' + self.playlist.selected_track()[PlayList.TITLE]+'"\n')

If you make this change and it works as expected, you can send us a patch and I will merge it. Follow the contributions guideline in case you want to contribute. https://github.com/KenT2/tboplayer/blob/master/CONTRIBUTING.md
