### ISSUE TITLE
Subtitles not loading from internet stream

### ISSUE THREAD

**Issue by edcarlo157** [KenT2/tboplayer#155]
Subtitles aren't been loaded from internet streams, I tried with youtube and with crunchyroll and no subtitles are available.

**Comment by heniotierra** [comment]
That's not an implemented feature. But it's an interesting thing to have.

**Comment by heniotierra** [comment]
This could be done by simply downloading the subtitle, temporarily saving it to the disk, and then passing it to omxplayer. However, since RPIs use sd memory, and these kind of memory have limit to how many times they can be written to, the best option is to create a virtual directory to store the downloaded subtitle.

**Comment by heniotierra** [comment]
https://github.com/KenT2/tboplayer/pull/156 implements this feature
