### ISSUE TITLE
Won't start - python 2 vs 3 confusion, tkinter.simpledialog.Dialog error

### ISSUE THREAD

**Issue by alazyworkaholic** [KenT2/tboplayer#181]
cloned repo, setup.sh ran without issues, then
```
$ tboplayer
python: can't open file '/opt/tboplayer/tboplayer.py': [Errno 2] No such file or directory
$ which tboplayer
/usr/local/bin/tboplayer
$ ls /opt/tboplayer/
Contributing.md lib license.md locale __main__.py README.md setup.sh
$ cat /usr/local/bin/tboplayer
#!/bin/bash
python /opt/tboplayer/tboplayer.py
$ sudo ln -s /opt/tboplayer/libs/tboplayer.py /opt/tboplayer/tboplayer.py
$ tboplayer
Traceback (most recent call last):
  File "/opt/tboplayer/lib/tboplayer.py", line 1703, in <module>
    class OptionsDialog(simpledialog.Dialog):
AttributeError: 'module' object has no attribute 'Dialog'
$ sudo tboplayer
Traceback (most recent call last):
  File "/opt/tboplayer/lib/tboplayer.py", line 2, in <module>
    from ytdl import *
  File "/opt/tboplayer/lib/ytdl.py", line 2, in <module>
    import pexpect
ImportError: No module named pexpect
$ python3 /opt/tboplayer/lib/tboplayer.py
$ 
```

The one-line script at /usr/local/bin/tboplayer pointed to a missing file. I found a file of the same name in libs so I sent it there via a symlink. Then it complains about the simpledialog module. My python's pitiful, but `from tkinter import simpledialog` worked in my python3 shell, which believes simpledialog.Dialog exists, but yielded the same AttributeError in my python2 shell, which seems to be what's called by /usr/local/bin/tboplayer. I'm confused, isn't this supposed to be the python3 version? I tried running it with `python3 /opt/tboplayer/tboplayer.py`, but it just exits silently after a moment. Running as root just yields a different error.

**Comment by heniotierra** [comment]
Hi, @alazyworkaholic ,

The python 3 version should be executed with

    python3 /opt/tboplayer/

However, a user reported an issue with the progress bar in this python3 version, although it works for other people. If you still run into issues after using the command above, make sure you're using python 3.7, since tboplayer was developed under python 3.7. If even then it fails, you still have the option to use the python2 version. https://github.com/KenT2/tboplayer/tree/py2_version

You would have fixed this problems if at least I had access to a Raspberry Pi ATM, but mine is hundreds of kilometers away, and with the COVID situation, I can't get it.
