### ISSUE TITLE
sudo pip install should not be used

### ISSUE THREAD

**Issue by Lartza** [KenT2/tboplayer#45]
In the installer and instructions, sudo pip install is used which is dangerous at worst and unstable at best. Packages from the OS repositories should be used instead, or another way.

**Comment by heniotierra** [comment]
Yes, that's because instaling pexpect through apt-get got me problems when trying to load ptyprocess, while pip installs makes it work with no problem. And installing pexpect/ptyprocess from source also gave me the same problem as apt-get, so I had no choice.

Why do you say pip is dangerous though? I get its packages are not so stable, but I'm unaware of any security issues aside of that.

**Comment by Lartza** [comment]
Running sudo pip runs setup.py as root, and that can have any code inside it.

The stability problem is less about the pip packages being stable, but your system being less stable when you go around your package manager and touch system files with pip. Worst case is obviously updating already existing packages but installing new ones ain't much better.

pip install --user or a virtualenv should be used instead
There is even a long standing issue on pip about this pypa/pip/#1668

**Comment by heniotierra** [comment]
Thanks, I will investigate this later.

**Comment by heniotierra** [comment]
This has been corrected: the README.md and setup.sh both have pip install --user.
